<?xml version="1.0" encoding="utf-8"?><Database Name="EFComLounge" Class="UpdatePasswordDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=INB-LANGEFCOMDB\SQL2008;Initial Catalog=EFComLounge;User ID=LoungeUser" SettingsObjectName="UpdateMyEFPassword.Properties.Settings" SettingsPropertyName="EFComLoungeConnectionString2" Provider="System.Data.SqlClient" />
  <Function Name="dbo.GetUsersToUpdatePasswordTemp" Method="GetUsersToUpdatePasswordTemp">
    <ElementType Name="GetUsersToUpdatePasswordTempResult">
      <Column Name="User_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MembershipId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.UpdatePasswordByUserIdTemp" Method="UpdatePasswordByUserIdTemp">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(512)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetExistingActivityMediaMigration" Method="GetExistingActivityMediaMigration">
    <Parameter Name="CalenderEventId" Parameter="calenderEventId" Type="System.Int32" DbType="Int" />
    <Parameter Name="TypeOfOperation" Parameter="typeOfOperation" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetExistingActivityMediaMigrationResult">
      <Column Name="Media_id" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CalendarEvent_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>